set nocompatible
set showcmd
set rnu

syntax on
filetype on
filetype plugin on
filetype indent on

colorscheme onedark
hi Comment guifg=#b7ffbd ctermfg=102
hi Normal guifg=#eeeeee guibg=#00000ee

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

let g:copilot_no_tab_map = v:true
let g:copilot_filetypes = {
	\ '*': v:false,
	\ 'gunk': v:true,
	\ }

" --BACKUP
set backup
set backupdir=~/.vim/backup/
set writebackup
set backupcopy=yes
au BufWritePre * let &bex = '@' . strftime("%F.%H:%M")

" --Display
set mouse=ar
set title
set number "Line numbers
set ruler
set wrap
set scrolloff=3
set lazyredraw
set termguicolors
set foldmethod=indent
set foldlevelstart=8 "Don't fold automatically unless really nested
set colorcolumn=101

" --Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" --Tab
set tabstop=4
set shiftwidth=4
set softtabstop=0

" --Beep
set visualbell
set noerrorbells

set backspace=indent,eol,start

set hidden

" --File Specific Configuration
autocmd BufRead,BufNewFile *.svelte set filetype=html
autocmd BufRead,BufNewFile *.gunk set filetype=gunk syntax=go colorcolumn=81 tw=80

" --My cute shortcuts
noremap // :nohls<CR>
inoremap jj <Esc>

noremap ,q :wqa<CR>
noremap ,w :edit<SPACE>
noremap ,e :Files<CR>
noremap ,r :so ~/.vimrc<CR>
noremap ,t :CocCommand explorer --toggle<CR>

noremap ,d :bp<CR>:bd #<CR>
noremap ,f :Rg<CR>
noremap ,h :help<SPACE>
noremap ,p :PrettierAsync<CR>

noremap <C-j> :bn<CR>
noremap <C-k> :bp<CR>

nmap <C-]> <Plug>(coc-definition)

" --Use right arrow instead of Tab for GitHub Copilot
inoremap <expr> <right> copilot#Accept("")

autocmd FileType cpp noremap ,c :!g++<SPACE>
autocmd FileType cpp map ,cf ,c"%"<CR>
autocmd FileType cpp map ,r ,c-o a ;./a;rm a<C-Left><C-Left>
autocmd FileType cpp map ,rf ,r"%"<CR>
