#!/bin/bash

if [ $1 = "up" ]; then
	pactl -- set-sink-volume 0 +5%
	pkill -SIGRTMIN+1 i3blocks
	exit 0
fi
if [ $1 = "down" ]; then
	pactl -- set-sink-volume 0 -5%
	pkill -SIGRTMIN+1 i3blocks
	exit 0
fi

echo "Unknown command. Expected $0 [up|down]."
