# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@cspell/dict-aws-1.0.14" = {
      name = "_at_cspell_slash_dict-aws";
      packageName = "@cspell/dict-aws";
      version = "1.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-aws/-/dict-aws-1.0.14.tgz";
        sha512 = "K21CfB4ZpKYwwDQiPfic2zJA/uxkbsd4IQGejEvDAhE3z8wBs6g6BwwqdVO767M9NgZqc021yAVpr79N5pWe3w==";
      };
    };
    "@cspell/dict-bash-1.0.17" = {
      name = "_at_cspell_slash_dict-bash";
      packageName = "@cspell/dict-bash";
      version = "1.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-bash/-/dict-bash-1.0.17.tgz";
        sha512 = "BlX+pnDlLmIf776C9d71QjXl4NOIz+yloeixx1ZZjrwvKPLF+ffE/Ez13eV+D9R2Ps1rW10UvW8u3Hbmwme+Fw==";
      };
    };
    "@cspell/dict-companies-1.0.40" = {
      name = "_at_cspell_slash_dict-companies";
      packageName = "@cspell/dict-companies";
      version = "1.0.40";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-companies/-/dict-companies-1.0.40.tgz";
        sha512 = "Aw07qiTroqSST2P5joSrC4uOA05zTXzI2wMb+me3q4Davv1D9sCkzXY0TGoC2vzhNv5ooemRi9KATGaBSdU1sw==";
      };
    };
    "@cspell/dict-cpp-1.1.40" = {
      name = "_at_cspell_slash_dict-cpp";
      packageName = "@cspell/dict-cpp";
      version = "1.1.40";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-cpp/-/dict-cpp-1.1.40.tgz";
        sha512 = "sscfB3woNDNj60/yGXAdwNtIRWZ89y35xnIaJVDMk5TPMMpaDvuk0a34iOPIq0g4V+Y8e3RyAg71SH6ADwSjGw==";
      };
    };
    "@cspell/dict-cryptocurrencies-1.0.10" = {
      name = "_at_cspell_slash_dict-cryptocurrencies";
      packageName = "@cspell/dict-cryptocurrencies";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-cryptocurrencies/-/dict-cryptocurrencies-1.0.10.tgz";
        sha512 = "47ABvDJOkaST/rXipNMfNvneHUzASvmL6K/CbOFpYKfsd0x23Jc9k1yaOC7JAm82XSC/8a7+3Yu+Fk2jVJNnsA==";
      };
    };
    "@cspell/dict-csharp-1.0.11" = {
      name = "_at_cspell_slash_dict-csharp";
      packageName = "@cspell/dict-csharp";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-csharp/-/dict-csharp-1.0.11.tgz";
        sha512 = "nub+ZCiTgmT87O+swI+FIAzNwaZPWUGckJU4GN402wBq420V+F4ZFqNV7dVALJrGaWH7LvADRtJxi6cZVHJKeA==";
      };
    };
    "@cspell/dict-css-1.0.12" = {
      name = "_at_cspell_slash_dict-css";
      packageName = "@cspell/dict-css";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-css/-/dict-css-1.0.12.tgz";
        sha512 = "K6yuxej7n454O7dwKG6lHacHrAOMZ0PhMEbmV6qH2JH0U4TtWXfBASYugHvXZCDDx1UObpiJP+3tQJiBqfGpHA==";
      };
    };
    "@cspell/dict-django-1.0.26" = {
      name = "_at_cspell_slash_dict-django";
      packageName = "@cspell/dict-django";
      version = "1.0.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-django/-/dict-django-1.0.26.tgz";
        sha512 = "mn9bd7Et1L2zuibc08GVHTiD2Go3/hdjyX5KLukXDklBkq06r+tb0OtKtf1zKodtFDTIaYekGADhNhA6AnKLkg==";
      };
    };
    "@cspell/dict-dotnet-1.0.32" = {
      name = "_at_cspell_slash_dict-dotnet";
      packageName = "@cspell/dict-dotnet";
      version = "1.0.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-dotnet/-/dict-dotnet-1.0.32.tgz";
        sha512 = "9H9vXrgJB4KF8xsyTToXO53cXD33iyfrpT4mhCds+YLUw3P3x3E9myszgJzshnrxYBvQZ+QMII57Qr6SjZVk4Q==";
      };
    };
    "@cspell/dict-elixir-1.0.26" = {
      name = "_at_cspell_slash_dict-elixir";
      packageName = "@cspell/dict-elixir";
      version = "1.0.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-elixir/-/dict-elixir-1.0.26.tgz";
        sha512 = "hz1yETUiRJM7yjN3mITSnxcmZaEyaBbyJhpZPpg+cKUil+xhHeZ2wwfbRc83QHGmlqEuDWbdCFqKSpCDJYpYhg==";
      };
    };
    "@cspell/dict-en-gb-1.1.33" = {
      name = "_at_cspell_slash_dict-en-gb";
      packageName = "@cspell/dict-en-gb";
      version = "1.1.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-en-gb/-/dict-en-gb-1.1.33.tgz";
        sha512 = "tKSSUf9BJEV+GJQAYGw5e+ouhEe2ZXE620S7BLKe3ZmpnjlNG9JqlnaBhkIMxKnNFkLY2BP/EARzw31AZnOv4g==";
      };
    };
    "@cspell/dict-en_us-1.2.45" = {
      name = "_at_cspell_slash_dict-en_us";
      packageName = "@cspell/dict-en_us";
      version = "1.2.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-en_us/-/dict-en_us-1.2.45.tgz";
        sha512 = "UPwR4rfiJCxnS+Py+EK9E4AUj3aPZE4p/yBRSHN+5aBQConlI0lLDtMceH5wlupA/sQTU1ERZGPJA9L96jVSyQ==";
      };
    };
    "@cspell/dict-filetypes-1.1.8" = {
      name = "_at_cspell_slash_dict-filetypes";
      packageName = "@cspell/dict-filetypes";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-filetypes/-/dict-filetypes-1.1.8.tgz";
        sha512 = "EllahNkhzvLWo0ptwu0l3oEeAJOQSUpZnDfnKRIh6mJVehuSovNHwA9vrdZ8jBUjuqcfaN2e7c32zN0D/qvWJQ==";
      };
    };
    "@cspell/dict-fonts-1.0.14" = {
      name = "_at_cspell_slash_dict-fonts";
      packageName = "@cspell/dict-fonts";
      version = "1.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-fonts/-/dict-fonts-1.0.14.tgz";
        sha512 = "VhIX+FVYAnqQrOuoFEtya6+H72J82cIicz9QddgknsTqZQ3dvgp6lmVnsQXPM3EnzA8n1peTGpLDwHzT7ociLA==";
      };
    };
    "@cspell/dict-fullstack-1.0.39" = {
      name = "_at_cspell_slash_dict-fullstack";
      packageName = "@cspell/dict-fullstack";
      version = "1.0.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-fullstack/-/dict-fullstack-1.0.39.tgz";
        sha512 = "Mbi+zWdiP9yzL+X4YD9Tgcm5YQ95Ql+Y3vF2LRnOY6g2QWaijTRN1rgksVuxzpFqHi//+bx2uoUb0XEKBYDi8g==";
      };
    };
    "@cspell/dict-golang-1.1.24" = {
      name = "_at_cspell_slash_dict-golang";
      packageName = "@cspell/dict-golang";
      version = "1.1.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-golang/-/dict-golang-1.1.24.tgz";
        sha512 = "qq3Cjnx2U1jpeWAGJL1GL0ylEhUMqyaR36Xij6Y6Aq4bViCRp+HRRqk0x5/IHHbOrti45h3yy7ii1itRFo+Xkg==";
      };
    };
    "@cspell/dict-haskell-1.0.13" = {
      name = "_at_cspell_slash_dict-haskell";
      packageName = "@cspell/dict-haskell";
      version = "1.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-haskell/-/dict-haskell-1.0.13.tgz";
        sha512 = "kvl8T84cnYRPpND/P3D86P6WRSqebsbk0FnMfy27zo15L5MLAb3d3MOiT1kW3vEWfQgzUD7uddX/vUiuroQ8TA==";
      };
    };
    "@cspell/dict-html-1.1.9" = {
      name = "_at_cspell_slash_dict-html";
      packageName = "@cspell/dict-html";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-html/-/dict-html-1.1.9.tgz";
        sha512 = "vvnYia0tyIS5Fdoz+gEQm77MGZZE66kOJjuNpIYyRHCXFAhWdYz3SmkRm6YKJSWSvuO+WBJYTKDvkOxSh3Fx/w==";
      };
    };
    "@cspell/dict-html-symbol-entities-1.0.23" = {
      name = "_at_cspell_slash_dict-html-symbol-entities";
      packageName = "@cspell/dict-html-symbol-entities";
      version = "1.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-html-symbol-entities/-/dict-html-symbol-entities-1.0.23.tgz";
        sha512 = "PV0UBgcBFbBLf/m1wfkVMM8w96kvfHoiCGLWO6BR3Q9v70IXoE4ae0+T+f0CkxcEkacMqEQk/I7vuE9MzrjaNw==";
      };
    };
    "@cspell/dict-java-1.0.23" = {
      name = "_at_cspell_slash_dict-java";
      packageName = "@cspell/dict-java";
      version = "1.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-java/-/dict-java-1.0.23.tgz";
        sha512 = "LcOg9srYLDoNGd8n3kbfDBlZD+LOC9IVcnFCdua1b/luCHNVmlgBx7e677qPu7olpMYOD5TQIVW2OmM1+/6MFA==";
      };
    };
    "@cspell/dict-latex-1.0.25" = {
      name = "_at_cspell_slash_dict-latex";
      packageName = "@cspell/dict-latex";
      version = "1.0.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-latex/-/dict-latex-1.0.25.tgz";
        sha512 = "cEgg91Migqcp1SdVV7dUeMxbPDhxdNo6Fgq2eygAXQjIOFK520FFvh/qxyBvW90qdZbIRoU2AJpchyHfGuwZFA==";
      };
    };
    "@cspell/dict-lorem-ipsum-1.0.22" = {
      name = "_at_cspell_slash_dict-lorem-ipsum";
      packageName = "@cspell/dict-lorem-ipsum";
      version = "1.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-lorem-ipsum/-/dict-lorem-ipsum-1.0.22.tgz";
        sha512 = "yqzspR+2ADeAGUxLTfZ4pXvPl7FmkENMRcGDECmddkOiuEwBCWMZdMP5fng9B0Q6j91hQ8w9CLvJKBz10TqNYg==";
      };
    };
    "@cspell/dict-lua-1.0.16" = {
      name = "_at_cspell_slash_dict-lua";
      packageName = "@cspell/dict-lua";
      version = "1.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-lua/-/dict-lua-1.0.16.tgz";
        sha512 = "YiHDt8kmHJ8nSBy0tHzaxiuitYp+oJ66ffCYuFWTNB3//Y0SI4OGHU3omLsQVeXIfCeVrO4DrVvRDoCls9B5zQ==";
      };
    };
    "@cspell/dict-node-1.0.12" = {
      name = "_at_cspell_slash_dict-node";
      packageName = "@cspell/dict-node";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-node/-/dict-node-1.0.12.tgz";
        sha512 = "RPNn/7CSkflAWk0sbSoOkg0ORrgBARUjOW3QjB11KwV1gSu8f5W/ij/S50uIXtlrfoBLqd4OyE04jyON+g/Xfg==";
      };
    };
    "@cspell/dict-npm-1.0.16" = {
      name = "_at_cspell_slash_dict-npm";
      packageName = "@cspell/dict-npm";
      version = "1.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-npm/-/dict-npm-1.0.16.tgz";
        sha512 = "RwkuZGcYBxL3Yux3cSG/IOWGlQ1e9HLCpHeyMtTVGYKAIkFAVUnGrz20l16/Q7zUG7IEktBz5O42kAozrEnqMQ==";
      };
    };
    "@cspell/dict-php-1.0.25" = {
      name = "_at_cspell_slash_dict-php";
      packageName = "@cspell/dict-php";
      version = "1.0.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-php/-/dict-php-1.0.25.tgz";
        sha512 = "RoBIP5MRdByyPaXcznZMfOY1JdCMYPPLua5E9gkq0TJO7bX5mC9hyAKfYBSWVQunZydd82HZixjb5MPkDFU1uw==";
      };
    };
    "@cspell/dict-powershell-1.0.19" = {
      name = "_at_cspell_slash_dict-powershell";
      packageName = "@cspell/dict-powershell";
      version = "1.0.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-powershell/-/dict-powershell-1.0.19.tgz";
        sha512 = "zF/raM/lkhXeHf4I43OtK0gP9rBeEJFArscTVwLWOCIvNk21MJcNoTYoaGw+c056+Q+hJL0psGLO7QN+mxYH1A==";
      };
    };
    "@cspell/dict-python-1.0.38" = {
      name = "_at_cspell_slash_dict-python";
      packageName = "@cspell/dict-python";
      version = "1.0.38";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-python/-/dict-python-1.0.38.tgz";
        sha512 = "KuyOQaby9NID/pn7EkXilpUxjVIvvyLzhr7BPsDS6FcvUE8Yhss6bJowEDHSv6pa+W2387phoqbDf2rTicquAA==";
      };
    };
    "@cspell/dict-ruby-1.0.15" = {
      name = "_at_cspell_slash_dict-ruby";
      packageName = "@cspell/dict-ruby";
      version = "1.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-ruby/-/dict-ruby-1.0.15.tgz";
        sha512 = "I76hJA///lc1pgmDTGUFHN/O8KLIZIU/8TgIYIGI6Ix/YzSEvWNdQYbANn6JbCynS0X+7IbZ2Ft+QqvmGtIWuA==";
      };
    };
    "@cspell/dict-rust-1.0.23" = {
      name = "_at_cspell_slash_dict-rust";
      packageName = "@cspell/dict-rust";
      version = "1.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-rust/-/dict-rust-1.0.23.tgz";
        sha512 = "lR4boDzs79YD6+30mmiSGAMMdwh7HTBAPUFSB0obR3Kidibfc3GZ+MHWZXay5dxZ4nBKM06vyjtanF9VJ8q1Iw==";
      };
    };
    "@cspell/dict-scala-1.0.21" = {
      name = "_at_cspell_slash_dict-scala";
      packageName = "@cspell/dict-scala";
      version = "1.0.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-scala/-/dict-scala-1.0.21.tgz";
        sha512 = "5V/R7PRbbminTpPS3ywgdAalI9BHzcEjEj9ug4kWYvBIGwSnS7T6QCFCiu+e9LvEGUqQC+NHgLY4zs1NaBj2vA==";
      };
    };
    "@cspell/dict-software-terms-1.0.48" = {
      name = "_at_cspell_slash_dict-software-terms";
      packageName = "@cspell/dict-software-terms";
      version = "1.0.48";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-software-terms/-/dict-software-terms-1.0.48.tgz";
        sha512 = "pfF3Ys2gRffu5ElqkH7FQMDMi/iZMyOzpGMb3FSH0PJ2AnRQ5rRNWght1h2L36YxvXl0mWVaFrrfwiOyRIc8ZQ==";
      };
    };
    "@cspell/dict-typescript-1.0.19" = {
      name = "_at_cspell_slash_dict-typescript";
      packageName = "@cspell/dict-typescript";
      version = "1.0.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspell/dict-typescript/-/dict-typescript-1.0.19.tgz";
        sha512 = "qmJApzoVskDeJnLZzZMaafEDGbEg5Elt4c3Mpg49SWzIHm1N4VXCp5CcFfHsOinJ30dGrs3ARAJGJZIw56kK6A==";
      };
    };
    "array-timsort-1.0.3" = {
      name = "array-timsort";
      packageName = "array-timsort";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-timsort/-/array-timsort-1.0.3.tgz";
        sha512 = "/+3GRL7dDAGEfM6TseQk/U+mi18TU2Ms9I3UlLdUMhz2hbvGNTKdj9xniwXfUqgYhHxRx0+8UnKkvlNwVU+cWQ==";
      };
    };
    "at-least-node-1.0.0" = {
      name = "at-least-node";
      packageName = "at-least-node";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/at-least-node/-/at-least-node-1.0.0.tgz";
        sha512 = "+q/t7Ekv1EDY2l6Gda6LLiX14rU9TV20Wa3ofeQmwPFZbOMo9DXrLbOjFaaclkXKWidIaopwAObQDqwWtGUjqg==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "comment-json-1.1.3" = {
      name = "comment-json";
      packageName = "comment-json";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/comment-json/-/comment-json-1.1.3.tgz";
        sha1 = "6986c3330fee0c4c9e00c2398cd61afa5d8f239e";
      };
    };
    "comment-json-4.1.1" = {
      name = "comment-json";
      packageName = "comment-json";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/comment-json/-/comment-json-4.1.1.tgz";
        sha512 = "v8gmtPvxhBlhdRBLwdHSjGy9BgA23t9H1FctdQKyUrErPjSrJcdDMqBq9B4Irtm7w3TNYLQJNH6ARKnpyag1sA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "configstore-5.0.1" = {
      name = "configstore";
      packageName = "configstore";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-5.0.1.tgz";
        sha512 = "aMKprgk5YhBNyH25hj8wGt2+D52Sw1DRRIzqBwLp2Ya9mFmY8KPvvtvmna8SxVR9JMZ4kzMD68N22vlaRpkeFA==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "crypto-random-string-2.0.0" = {
      name = "crypto-random-string";
      packageName = "crypto-random-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-2.0.0.tgz";
        sha512 = "v1plID3y9r/lPhviJ1wrXpLeyUIGAZ2SHNYTEapm7/8A9nLPoyvVp3RK/EPFqn5kEznyWgYZNsRtYYIWbuG8KA==";
      };
    };
    "cspell-dict-vimlang-1.0.1" = {
      name = "cspell-dict-vimlang";
      packageName = "cspell-dict-vimlang";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-dict-vimlang/-/cspell-dict-vimlang-1.0.1.tgz";
        sha512 = "pP2W2BvLrRKggS1fUk8qQw2FG8PhyV969dlwF3M0jAg/HH83n76H+KGdzGsmEut6VJFlJYQkd1ZZskjaeVWnrA==";
      };
    };
    "cspell-glob-0.1.25" = {
      name = "cspell-glob";
      packageName = "cspell-glob";
      version = "0.1.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-glob/-/cspell-glob-0.1.25.tgz";
        sha512 = "/XaSHrGBpMJa+duFz3GKOWfrijrfdHT7a/XGgIcq3cymCSpOH+DPho42sl0jLI/hjM+8yv2m8aEoxRT8yVSnlg==";
      };
    };
    "cspell-io-4.1.7" = {
      name = "cspell-io";
      packageName = "cspell-io";
      version = "4.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-io/-/cspell-io-4.1.7.tgz";
        sha512 = "V0/tUu9FnIS3v+vAvDT6NNa14Nc/zUNX8+YUUOfFAiDJJTdqefmvcWjOJBIMYBf3wIk9iWLmLbMM+bNHqr7DSQ==";
      };
    };
    "cspell-lib-4.3.12" = {
      name = "cspell-lib";
      packageName = "cspell-lib";
      version = "4.3.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-lib/-/cspell-lib-4.3.12.tgz";
        sha512 = "yCCb6MoW1K8Tsr/WVEQoO4dfYhH9bCsjQayccb8MlyDaNNuWJHuX+gUGHsZSXSuChSh8PrTWKXJzs13/uM977g==";
      };
    };
    "cspell-trie-lib-4.2.8" = {
      name = "cspell-trie-lib";
      packageName = "cspell-trie-lib";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-trie-lib/-/cspell-trie-lib-4.2.8.tgz";
        sha512 = "Nt3c0gxOYXIc3/yhALDukpje1BgR6guvlUKWQO2zb0r7qRWpwUw2j2YM4dWbHQeH/3Hx5ei4Braa6cMaiJ5YBw==";
      };
    };
    "cspell-util-bundle-4.1.11" = {
      name = "cspell-util-bundle";
      packageName = "cspell-util-bundle";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cspell-util-bundle/-/cspell-util-bundle-4.1.11.tgz";
        sha512 = "or3OGKydZs1NwweMIgnA48k8H3F5zK4e5lonjUhpEzLYQZ2nB23decdoqZ8ogFC8pFTA40tZKDsMJ0b+65gX4Q==";
      };
    };
    "dot-prop-5.3.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-5.3.0.tgz";
        sha512 = "QM8q3zDe58hqUqjraQOmzZ1LIH9SWQJTlEKCH4kJ2oQvLZk7RbQXvtDM2XEq3fwkV9CCvvH4LA0AV+ogFsBM2Q==";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "fs-extra-8.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz";
        sha512 = "yhlQgA6mnOJUKOsRUFsgJdQCvkKhcz8tlZG5HBQfReYZy46OwLcY+Zia0mtdHsOo9y/hP+CxMN0TU9QxoOtG4g==";
      };
    };
    "fs-extra-9.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "9.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-9.1.0.tgz";
        sha512 = "hcg3ZmepS30/7BSFqRvoo3DOMQu7IjqxO5nCDt+zM9XWjb33Wg7ziNT+Qvqbuc3+gWpzO02JubVyk2G4Zvo1OQ==";
      };
    };
    "gensequence-2.3.0" = {
      name = "gensequence";
      packageName = "gensequence";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensequence/-/gensequence-2.3.0.tgz";
        sha512 = "XrmtQsfTd1Mdt60fNG3sDpmo7yX3UaCd2RzrfWGbgE86H2k/pppGs84zFV2WSh9UwXIVNs0O62HeIrxIcTZntQ==";
      };
    };
    "gensequence-3.1.1" = {
      name = "gensequence";
      packageName = "gensequence";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensequence/-/gensequence-3.1.1.tgz";
        sha512 = "ys3h0hiteRwmY6BsvSttPmkhC0vEQHPJduANBRtH/dlDPZ0UBIb/dXy80IcckXyuQ6LKg+PloRqvGER9IS7F7g==";
      };
    };
    "global-dirs-0.1.1" = {
      name = "global-dirs";
      packageName = "global-dirs";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-dirs/-/global-dirs-0.1.1.tgz";
        sha1 = "b319c0dd4607f353f3be9cca4c72fc148c49f445";
      };
    };
    "graceful-fs-4.2.8" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.8.tgz";
        sha512 = "qkIilPUYcNhJpd33n0GBXTB1MMPp14TxEsEs0pTrsSVucApsYzW5V+Q8Qxhik6KU3evy+qkAAowTByymK0avdg==";
      };
    };
    "has-own-prop-2.0.0" = {
      name = "has-own-prop";
      packageName = "has-own-prop";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-own-prop/-/has-own-prop-2.0.0.tgz";
        sha512 = "Pq0h+hvsVm6dDEa8x82GnLSYHOzNDt7f0ddFa3FqcQlgzEiptPqL+XrOJNavjOzSYiYWIrgeVYYgGlLmnxwilQ==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "iterable-to-stream-1.0.1" = {
      name = "iterable-to-stream";
      packageName = "iterable-to-stream";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterable-to-stream/-/iterable-to-stream-1.0.1.tgz";
        sha512 = "O62gD5ADMUGtJoOoM9U6LQ7i4byPXUNoHJ6mqsmkQJcom331ZJGDApWgDESWyBMEHEJRjtHozgIiTzYo9RU4UA==";
      };
    };
    "json-parser-1.1.5" = {
      name = "json-parser";
      packageName = "json-parser";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parser/-/json-parser-1.1.5.tgz";
        sha1 = "e62ec5261d1a6a5fc20e812a320740c6d9005677";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "make-dir-3.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-3.1.0.tgz";
        sha512 = "g3FeP20LNwhALb/6Cz6Dd4F2ngze0jz7tbzrD2wAV+o9FeNHe4rL+yK2md0J/fiSf1sa1ADhXqi5+oVwOM/eGw==";
      };
    };
    "micromatch-4.0.4" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.4.tgz";
        sha512 = "pRmzw/XUcwXGpD9aI9q/0XOwLNygjETJ8y0ao0wdqprrzDa4YnxLcz7fQRZr8voh8V10kGhABbNcHVk5wHgWwg==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "node-watch-0.6.4" = {
      name = "node-watch";
      packageName = "node-watch";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-watch/-/node-watch-0.6.4.tgz";
        sha512 = "cI6CHzivIFESe8djiK3Wh90CtWQBxLwMem8x8S+2GSvCvFgoMuOKVlfJtQ/2v3Afg3wOnHl/+tXotEs8z5vOrg==";
      };
    };
    "picomatch-2.3.0" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.0.tgz";
        sha512 = "lY1Q/PiJGC2zOv/z391WOTD+Z02bCgsFfvxoXXf6h7kv9o+WmsmzYqrAwY63sNgOxE4xEdq0WyUnXfKeBrSvYw==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "resolve-global-1.0.0" = {
      name = "resolve-global";
      packageName = "resolve-global";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-global/-/resolve-global-1.0.0.tgz";
        sha512 = "zFa12V4OLtT5XUX/Q4VLvTfBf+Ok0SPc1FNGM/z9ctUdiU618qwKpWnd0CHs3+RqROfyEg/DhuHbMWYqcgljEw==";
      };
    };
    "rxjs-6.6.7" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "6.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-6.6.7.tgz";
        sha512 = "hTdwr+7yYNIT5n4AMYp85KA6yw2Va0FLa3Rguvbpa4W3I5xynaBZo41cM3XM+4Q6fRMj3sBYIR1VAmZMXYJvRQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "signal-exit-3.0.6" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.6.tgz";
        sha512 = "sDl4qMFpijcGw22U5w63KmD3cZJfBuFlVNbVMKje2keoKML7X2UzWbc4XrmEbDwg0NXJc3yv4/ox7b+JWb57kQ==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "unique-string-2.0.0" = {
      name = "unique-string";
      packageName = "unique-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-string/-/unique-string-2.0.0.tgz";
        sha512 = "uNaeirEPvpZWSgzwsPGtU2zVSTrn/8L5q/IexZmH0eH6SA73CmAA5U4GwORTxQAZs95TAXLNqeLoPPNO5gZfWg==";
      };
    };
    "universalify-0.1.2" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
        sha512 = "rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "vscode-jsonrpc-4.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-4.0.0.tgz";
        sha512 = "perEnXQdQOJMTDFNv+UF3h1Y0z4iSiaN9jIlb0OqIYgosPCZGYh/MCUlkFtV2668PL69lRDO32hmvL2yiidUYg==";
      };
    };
    "vscode-languageserver-5.2.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-5.2.1.tgz";
        sha512 = "GuayqdKZqAwwaCUjDvMTAVRPJOp/SLON3mJ07eGsx/Iq9HjRymhKWztX41rISqDKhHVVyFM+IywICyZDla6U3A==";
      };
    };
    "vscode-languageserver-protocol-3.14.1" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.14.1.tgz";
        sha512 = "IL66BLb2g20uIKog5Y2dQ0IiigW0XKrvmWiOvc0yXw80z3tMEzEnHjaGAb3ENuU7MnQqgnYJ1Cl2l9RvNgDi4g==";
      };
    };
    "vscode-languageserver-types-3.14.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.14.0.tgz";
        sha512 = "lTmS6AlAlMHOvPQemVwo3CezxBp0sNB95KNPkqp3Nxd5VFEnuG1ByM0zlRWos0zjO3ZWtkvhal0COgiV1xIA4A==";
      };
    };
    "vscode-uri-1.0.8" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-1.0.8.tgz";
        sha512 = "obtSWTlbJ+a+TFRYGaUumtVwb+InIUVI0Lu0VBUAPmj2cU5JutEXg3xUE0c2J5Tcy7h2DEKVJBFi+Y9ZSFzzPQ==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
    "vscode-uri-3.0.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.2.tgz";
        sha512 = "jkjy6pjU1fxUvI51P+gCsxg1u2n8LSt0W6KrCNQceaziKzff74GoWmjVG46KieVzybO1sttPQmYfrwSHey7GUA==";
      };
    };
    "write-file-atomic-3.0.3" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-3.0.3.tgz";
        sha512 = "AvHcyZ5JnSfq3ioSyjrBkH9yW4m7Ayk8/9My/DD9onKeu/94fwrMocemO2QAJFAlnnDN+ZDS+ZjAR5ua1/PV/Q==";
      };
    };
    "xdg-basedir-4.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-4.0.0.tgz";
        sha512 = "PSNhEJDejZYV7h50BohL09Er9VaIefr2LMAf3OEmpCkjOi34eYyQYAXUTjEQtZJTKcF0E2UKTh+osDLsgNim9Q==";
      };
    };
  };
in
{
  coc-spell-checker = nodeEnv.buildNodePackage {
    name = "coc-spell-checker";
    packageName = "coc-spell-checker";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-spell-checker/-/coc-spell-checker-1.2.0.tgz";
      sha512 = "TuwqtkoDN8MvxLNC7R0932vgAVY+eRIrL4dZoWtIhgQF3WTlIAQBrgC0AHuF0v8q/QeZU8hxEqDIyfTwIKXXJw==";
    };
    dependencies = [
      sources."@cspell/dict-aws-1.0.14"
      sources."@cspell/dict-bash-1.0.17"
      sources."@cspell/dict-companies-1.0.40"
      sources."@cspell/dict-cpp-1.1.40"
      sources."@cspell/dict-cryptocurrencies-1.0.10"
      sources."@cspell/dict-csharp-1.0.11"
      sources."@cspell/dict-css-1.0.12"
      sources."@cspell/dict-django-1.0.26"
      sources."@cspell/dict-dotnet-1.0.32"
      sources."@cspell/dict-elixir-1.0.26"
      sources."@cspell/dict-en-gb-1.1.33"
      sources."@cspell/dict-en_us-1.2.45"
      sources."@cspell/dict-filetypes-1.1.8"
      sources."@cspell/dict-fonts-1.0.14"
      sources."@cspell/dict-fullstack-1.0.39"
      sources."@cspell/dict-golang-1.1.24"
      sources."@cspell/dict-haskell-1.0.13"
      sources."@cspell/dict-html-1.1.9"
      sources."@cspell/dict-html-symbol-entities-1.0.23"
      sources."@cspell/dict-java-1.0.23"
      sources."@cspell/dict-latex-1.0.25"
      sources."@cspell/dict-lorem-ipsum-1.0.22"
      sources."@cspell/dict-lua-1.0.16"
      sources."@cspell/dict-node-1.0.12"
      sources."@cspell/dict-npm-1.0.16"
      sources."@cspell/dict-php-1.0.25"
      sources."@cspell/dict-powershell-1.0.19"
      sources."@cspell/dict-python-1.0.38"
      sources."@cspell/dict-ruby-1.0.15"
      sources."@cspell/dict-rust-1.0.23"
      sources."@cspell/dict-scala-1.0.21"
      sources."@cspell/dict-software-terms-1.0.48"
      sources."@cspell/dict-typescript-1.0.19"
      sources."array-timsort-1.0.3"
      sources."at-least-node-1.0.0"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."comment-json-1.1.3"
      sources."concat-map-0.0.1"
      sources."configstore-5.0.1"
      sources."core-util-is-1.0.3"
      sources."crypto-random-string-2.0.0"
      sources."cspell-dict-vimlang-1.0.1"
      sources."cspell-glob-0.1.25"
      (sources."cspell-io-4.1.7" // {
        dependencies = [
          sources."iconv-lite-0.6.3"
        ];
      })
      (sources."cspell-lib-4.3.12" // {
        dependencies = [
          sources."comment-json-4.1.1"
          sources."esprima-4.0.1"
          sources."fs-extra-9.1.0"
          sources."gensequence-3.1.1"
          sources."vscode-uri-3.0.2"
        ];
      })
      (sources."cspell-trie-lib-4.2.8" // {
        dependencies = [
          sources."gensequence-3.1.1"
        ];
      })
      sources."cspell-util-bundle-4.1.11"
      sources."dot-prop-5.3.0"
      sources."esprima-2.7.3"
      sources."fill-range-7.0.1"
      (sources."fs-extra-8.1.0" // {
        dependencies = [
          sources."jsonfile-4.0.0"
          sources."universalify-0.1.2"
        ];
      })
      sources."gensequence-2.3.0"
      sources."global-dirs-0.1.1"
      sources."graceful-fs-4.2.8"
      sources."has-own-prop-2.0.0"
      sources."iconv-lite-0.4.24"
      sources."imurmurhash-0.1.4"
      sources."ini-1.3.8"
      sources."is-number-7.0.0"
      sources."is-obj-2.0.0"
      sources."is-typedarray-1.0.0"
      sources."iterable-to-stream-1.0.1"
      sources."json-parser-1.1.5"
      sources."jsonfile-6.1.0"
      sources."make-dir-3.1.0"
      sources."micromatch-4.0.4"
      sources."minimatch-3.0.4"
      sources."node-watch-0.6.4"
      sources."picomatch-2.3.0"
      sources."repeat-string-1.6.1"
      sources."resolve-from-5.0.0"
      sources."resolve-global-1.0.0"
      sources."rxjs-6.6.7"
      sources."safer-buffer-2.1.2"
      sources."semver-6.3.0"
      sources."signal-exit-3.0.6"
      sources."to-regex-range-5.0.1"
      sources."tslib-1.14.1"
      sources."typedarray-to-buffer-3.1.5"
      sources."unique-string-2.0.0"
      sources."universalify-2.0.0"
      sources."vscode-jsonrpc-4.0.0"
      (sources."vscode-languageserver-5.2.1" // {
        dependencies = [
          sources."vscode-uri-1.0.8"
        ];
      })
      sources."vscode-languageserver-protocol-3.14.1"
      sources."vscode-languageserver-types-3.14.0"
      sources."vscode-uri-2.1.2"
      sources."write-file-atomic-3.0.3"
      sources."xdg-basedir-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Spelling checker for source code";
      homepage = "https://github.com/iamcco/coc-spell-checker";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
