# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  coc-gunk = nodeEnv.buildNodePackage {
    name = "coc-gunk";
    packageName = "coc-gunk";
    version = "0.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-gunk/-/coc-gunk-0.0.3.tgz";
      sha512 = "xtdBLCz/Qah5o+zL21qWtzx9QJ9/CnQlcNs77R4YrsB1FDdJ6GpqNKyRT3zLFlF5bRDL6hbPflSOh+HyHvb3Ag==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
